### ISSUE TITLE
getSigninUrl() is not taking the Grant Types into account

### ISSUE THREAD

**Issue by KrishnaPG** [casdoor/casdoor-js-sdk#29]
The implementation of `getSigninUrl()` currently is hardcoded for [Authorization Code Grant Type](https://casdoor.org/docs/how-to-connect/oauth#authorization-code-grant-)

https://github.com/casdoor/casdoor-js-sdk/blob/72d558769d5cfd7d97ea9d2b77c2027b4f0c2b54/src/sdk.ts#L58-L63

- It has to take grant type into account and construct the appropriate URL for all other relevant Grant Types too.

![image](https://user-images.githubusercontent.com/4610831/172976332-e4238792-63f5-469f-b354-d9eda65e5ff6.png)

- Also, there should be a way to retrieve the configured grant types from the CASDoor Server for a given application. (Or better yet, automatically build the URL from one of the configured grant types for the application by talking to the casdoor server)

**Comment by hsluoyz** [comment]
Hi @KrishnaPG 

> It has to take grant type into account and construct the appropriate URL for all other relevant Grant Types too.

How to do this? Can you be more specific?

> Also, there should be a way to retrieve the configured grant types from the CASDoor Server for a given application. (Or better yet, automatically build the URL from one of the configured grant types for the application by talking to the casdoor server)

You can use the `GetApplication()` API: https://door.casdoor.com/swagger/#/Application%20API/ApiController.GetApplication

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 @leo220yuyaodog

**Comment by hsluoyz** [comment]
Closed as resolved
