### ISSUE TITLE
Add README, CI and code coverage badges and semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-js-sdk#3]

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@hsluoyz I'm not familiar with this project. Could @Kininaru work on this?

**Comment by hsluoyz** [comment]
@WindSpiritSR

**Comment by hsluoyz** [comment]
@ErikQQY

**Comment by hsluoyz** [comment]
@ErikQQY because of a severe bug, all versions after v1.0.0 (included) are published with an empty package. Actually the semantic-release PR: https://github.com/casdoor/casdoor-js-sdk/pull/7 is wrong.

So I have rolled back all those wrong releases and commits. We need to re-do the integration with semantic-release in a correct way.

**Comment by hsluoyz** [comment]
Done by: https://github.com/casdoor/casdoor-js-sdk/pull/10 and https://github.com/casdoor/casdoor-js-sdk/pull/11

**Comment by hsluoyz** [comment]
@seriouszyx @Steve0x2a

**Comment by hsluoyz** [comment]
@fabian4
