### ISSUE TITLE
singin API  parameter verified failed, got an random string of the "state".

### ISSUE THREAD

**Issue by Airren** [casdoor/casdoor-js-sdk#46]
<img width="801" alt="image" src="https://github.com/casdoor/casdoor-js-sdk/assets/14846116/07f504a9-53be-4616-9bf9-9515cbf79468">
<img width="796" alt="image" src="https://github.com/casdoor/casdoor-js-sdk/assets/14846116/9ba1e5c3-b7e4-4710-8977-cfc875ff2189">

**Comment by Airren** [comment]
```json
    "casdoor-js-sdk": "^0.3.0",
    "casdoor-react-sdk": "^1.1.0",
```
This version is worked for me.

**Comment by hsluoyz** [comment]
@Airren so are you using newer versions? latest version is correct, right?

**Comment by ci0n** [comment]
No,i use casdoor-js-sdk@0.13.0, there will be the same problem

**Comment by hsluoyz** [comment]
@ci0n have you tried the example like: https://github.com/casdoor/casdoor-nodejs-react-example ?

**Comment by ci0n** [comment]
Oh, no, it's my problem. Sorry for wasting your time.
